name: Playwright Tests
on:
  push:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '18'  # Use a specific Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Set up environment variables
      run: |
        echo "URL=${{ secrets.URL }}" >> $GITHUB_ENV
        echo "RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY }}" >> $GITHUB_ENV
        echo "RAPIDAPI_HOST=${{ secrets.RAPIDAPI_HOST }}" >> $GITHUB_ENV

    - name: Run Playwright tests
      run: npm test
